using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace netmon.domain.Models
{
    public class StorageBase
    {
        /// <summary>
        /// Autogenerated unqiue identifier for response.
        /// </summary>
        [BsonElement("_id")][BsonRepresentation(BsonType.String)] public Guid Id { get; set; } = Guid.NewGuid();
    }
}