version: '3.4'

services:
  netmon.cli:
    image: ${DOCKER_REGISTRY-}netmoncli
    build:
      context: .
      dockerfile: netmon.cli/Dockerfile
    volumes:
        - ${APPDATA}/netmon/data:/usr/share/netmon ## Environment.SpecialFolder.CommonApplicationData/netmon