version: '3.4'

services:
  netmon.cli.monitor:
    image: ${DOCKER_REGISTRY-}netmonclimonitor
    build:
      context: .
      dockerfile: netmon.cli.monitor/Dockerfile
    volumes:
        - ${APPDATA}/netmon:/usr/share/netmon ## Environment.SpecialFolder.CommonApplicationData/netmon
  netmon.cli.store:
    image: ${DOCKER_REGISTRY-}netmonclistore
    build:
      context: .
      dockerfile: netmon.cli.store/Dockerfile
    volumes:
        - ${APPDATA}/netmon:/usr/share/netmon ## Environment.SpecialFolder.CommonApplicationData/netmon